### ISSUE TITLE
Add audio?

### ISSUE THREAD

**Issue by hendog518** [Pomax/arduino-midi-recorder#10]
Have you considered a version of this project that also records audio? 

I don’t know the first thing about this stuff (if I make this, it’d be my first arduino project) and how much complexity that would add, but for synths and drum machines and other MIDI toys that one might like to use without a pc, I think a parallel recording of the actual audio (and a similar “audio in / audio thru” setup) would add very handy functionality.

**Comment by Pomax** [comment]
Given that there are a million fantastic inline audio recorders available at almost every price point: nope. No point, for the cost of an arduino and circuitry, you can get a better assembled, price-appropriate quality consumer device that comes with a manufacturer and shop warranty =)
