### ISSUE TITLE
Playback  & SysEx?

### ISSUE THREAD

**Issue by Klokdoc** [Pomax/arduino-midi-recorder#11]
First of all, what a good idea.  I'm still using a 3 1/2" disc recorder/player which is becoming unreliable.
I'd like to build a similar device that would also play back.   I'd have to record all the SysEx codes as well, my instrument relies on them.  It's a three manual electronic organ with pedals so has four channels, all on one track, and stops, swell pedals, etc are all done by SysEx codes (0F?).  MIDI files produced by this instrument will only work on this instrument, it's a custom design.
Is this feasible?
Thanks,
Chris

**Comment by ColbyDAllen** [comment]
How hard would it be to implement a looper with Play/Record functionality that updates an existing SMF format 0 .mid file during playback? 

Say you're trying to recorder a drum pattern for instance, so only one channel is needed, and you're just playing a different pitch assigned to a different percussion instrument. Could you write a second line over your first pattern on the same channel, different pitch? Like an audio overdub, but a midi-overdub? Like this:

|| "I'm MIDI file (A)...                                   ...and together we are..." ||
||                          "And I'm MIDI file (B)... ...and together we are..." ||

ONE .MID FILE!!! Lol.

Or maybe simultaneous play record would only be possible if the file being recorded to was not the same one being played?

Just trying to wrap my head around feasibility, whether I'd need a second storage device for playback, or if a fresh overhaul would make more sense.

Best,
Colby

**Comment by Pomax** [comment]
That sounds like a MIDI looper, of which there are many already =)

**Comment by ColbyDAllen** [comment]
Beautiful! I've tried nearly every other combination of keywords, especially "sequencer" -related projects, but I see you're not kidding. Will be looking into this tomorrow. Thank you.

**Comment by ColbyDAllen** [comment]
I was mulling this over this morning, not necesarily SysEx events, but have calls/callbacks outside of the <MIDI.h> looping Note-On events:

Do you think it's possible to have multiple calls to the "void writeToFile(byteType, byte b1, byte b2, int delta)" function?

```
/*
    For instance have the original:
*/
void handleNoteOn(byte channel, byte pitch, byte velocity) {
  writeToFile(NOTE_ON_EVENT, pitch, velocity);
}

/*
    AND have separate function:
*/
void ThisNoteLOOPED(byte channel, byte pitch, byte velocity) {  
  writeToFile(NOTE_ON_EVENT, pitch, velocity);
}
```
...working simultaneously...

```
/*
    ...both being fed into the function:
*/
void writeToFile(byte eventType, byte b1, byte b2, int delta) {
  if (!file) return;
  writeVarLen(file, delta);
  file.write(eventType);
  file.write(b1);
  file.write(b2);
}
```

...without breaking how the bytes are being fed to the SD card?

**Comment by ColbyDAllen** [comment]
There's a much larger sketch I'm using to toy with this idea, but the above is the distilled concept. Obviously you'd want a corresponding "void ThisNoteOffLOOPED" function for the additional stream of notes...

Happy to share the full sketch if you'd be interested. 

Best,
Colby

**Comment by Pomax** [comment]
no, what you wrote as "simultaneous" code will write completely different bytes.

(note that I'm closing this issue mostly because we drifted well away from the original issue at this point)

**Comment by ColbyDAllen** [comment]
Sorry about that, and got you. Thanks for clarifying!

**Comment by Pomax** [comment]
feel free to open a new issue though!
