### ISSUE TITLE
[SOLVED] recorded MIDI files are not useable or corrupt

### ISSUE THREAD

**Issue by othmar52** [Pomax/arduino-midi-recorder#8]
@Pomax thank you for this great project and the detailed documentation!!!  
Currently i am trying to build my own recorder with an Arduino UNO R3 and a [TFT/SD shield](https://create.arduino.cc/projecthub/javagoza/2-4-tft-lcd-touch-display-road-test-89f51b) based on your sketch.  

Due to the huge amount of PINS used by the shield i have no button for creating markers or any kind of audio debug.  
Currently i do not use a RTC as well but i am going to implement this as soon as everything works.  

my TFT shows an incoming-note-indicator, incoming cc-indicator, the current filename of the recording and the recording time.  
so everything works as expected except one thing:  

The created MIDI files seems to be corrupt or not readable.  
I tried different kinds of midi file supporting software. One of those is [upload form of onlinesequencer.net](https://onlinesequencer.net/import).  

The error message of the "vanilla version" reads:
```
Could not parse MIDI file: Track data exceeds expected length (1/0)
```
After fixing the track_length bytes with `fix.py` i get a different error:
```
Could not parse MIDI file: Track data exceeds expected length (59/56)
```
I also tried to manipulate the calculation of track_length in `fix.py` to avoid the error above but then i get:  
```
Unexpected EOF
```

As `.mid`files are not attachable i have created a `.zip` with short recordings of 3 noteOn + noteOff events.  
[test-recordings-vanilla-and-fixed.zip](https://github.com/Pomax/arduino-midi-recorder/files/6195740/test-recordings-vanilla-and-fixed.zip)  
```
FILE-061-vanilla.MID
FILE-061-fixed_length.MID
```

I used `FAT16` filesystem for the SD.  
Obviously there are some bytes in the recordings that shouldn't be there, right?  
Do you have any hint how to fix this?

**Comment by othmar52** [comment]
i solved it myself:  
after formatting the SD card with `FAT32` instead of `FAT16` everything worked

**Comment by Pomax** [comment]
Yeah, never use FAT16.
