### ISSUE TITLE
[QUESTION] how to add license in fork?

### ISSUE THREAD

**Issue by othmar52** [Pomax/arduino-midi-recorder#9]
@Pomax As you might have noticed i have created a [fork with a lot of changes](https://github.com/othmar52/arduino-midi-recorder) based on your repository.  
I kept your license notice in the main sketch file.  
Please tell me if this enough or if a have to do more in terms of license.  
I don't want to violate any license agreements!

**Comment by Pomax** [comment]
https://github.com/Pomax/arduino-midi-recorder/blob/master/midi-recorder.ino#L379-L388

If you live in a jurisdiction that does not recognize the public domain (France etc), then the code is MIT licensed and you can act in accordance to that - if you live anywhere else, my code is public domain code meaning you're literally free to do whatever you like with it =)

**Comment by Pomax** [comment]
That said, I'm not sure how your code works, given that the .mid file hex setup and `writeToFile` function seem to be missing?

**Comment by othmar52** [comment]
> meaning you're literally free to do whatever you like with it =)

Thank you for clarification!

> ... it looks like you removed the the .mid file hex setup, as well as the writeToFile function?

No, i only removed the createMarker and the debugAudio stuff. i prefer to have multiple `.ino`'s for better maintainability.  
Pretty sure you already know that all existing `.ino`'s gets concatenated during compiling within most ide's!? Case not, maybe you will try it yourself on your next huge sketch.


> ...Now you need a computer...  

No, i don't use a computer in my synth setup. but a few standalone midi interfaces with lots of routing options (iConnectivity 1x `mioXL` + 2x `ICM4+`). But you are right, theroretically it is possible to have it inline in my routing but it does not make any sense.  
Maybe i'll add a DIN midi in+out too. In my testing of other arduino+midi projects i noticed that USB- and DIN-midi works both without changing anything in the sketch


> ...at the very least, mac and windows...

I dont have those OS. But in general it does not make sense to send midi to an arduino for recording. In such a scenario i would prefer to record the midi directly on the pc.

**Comment by Pomax** [comment]
>No, i only removed the createMarker and the debugAudio stuff

I searched your code for writeToFile and don't see it in any of the ino files though?

**Comment by othmar52** [comment]
> I searched your code for writeToFile and don't see it in any of the ino files though?

stille there: [20-sd-rtc.ino#L143](https://github.com/othmar52/arduino-midi-recorder/blob/c363afa340de0b1840fa705fc41532facdc41b6e/20-sd-rtc.ino#L143)

**Comment by Pomax** [comment]
oh, interesting that github didn't find it when I used their code search. Then again, their code search has never been all that good...
